name: Kodi Addon-Submitter

on:
  create:
    tags:
      - v*

jobs:
  kodi-addon-submitter:
    runs-on: ubuntu-latest
    name: Kodi addon submitter
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract target official repo branch
      id: extract_branch_pr
      shell: bash
      run:
        echo "##[set-output name=branch;]$(git --no-pager branch -a --contains "$GITHUB_SHA" | grep 'remotes/origin/' | cut -d '/' -f3)" && \
        echo "##[set-output name=addonid;]$(echo $GITHUB_REF | cut -d '/' -f2)"

    - name: echoer
      id: echoer
      shell: bash
      run:
        echo "${{ steps.extract_branch_pr.outputs.branch }}"
        echo "${{ steps.extract_branch_pr.outputs.addonid }}"

    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: xbmc/action-kodi-addon-checker@v1.0
      with:
        kodi-version: ${{ steps.extract_branch_pr.outputs.branch }}
