name: Kodi Addon-Submitter

on:
  create:
    tags:
      - v*

jobs:
  kodi-addon-submitter:
    runs-on: ubuntu-latest
    name: Kodi addon submitter
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Extract target official repo branch
      shell: bash
      run: echo "##[set-output name=branch;]$(git --no-pager branch -a --contains 1.0.0+krypton.5 | grep "*")
      id: extract_branch
    - name: Echo branch containing the version tag
      shell: bash
      run: echo ${{ steps.extract_branch.outputs.branch }}