name: Kodi Addon-Submitter

on:
  create:
    tags:
      - v*

jobs:
  kodi-addon-submitter:
    runs-on: ubuntu-latest
    name: Kodi addon submitter
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract kodi official repository target
      id: extract_branch_pr
      shell: bash
      env:
        ADDON_ID: ${{ github.event.repository.name }}
      run: |
        echo "##[set-output name=branch;]$(git --no-pager branch -a --contains "$GITHUB_SHA" | grep 'remotes/origin/' | cut -d '/' -f3)"
        if [[ $ADDON_ID == plugin* ]]; then
            echo "##[set-output name=repo;]repo-plugins"
        else
            echo "##[set-output name=repo;]repo-scripts"
        fi

    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: xbmc/action-kodi-addon-checker@v1.0
      with:
        kodi-version: ${{ steps.extract_branch_pr.outputs.branch }}

    - name: Generate distribution zip and submit to official kodi repository
      id: kodi-addon-submitter
      uses: xbmc/action-kodi-addon-submitter@v1.1
      with: # Replace all the below values
        kodi-repository: ${{ steps.extract_branch_pr.outputs.repo }}
        kodi-version: ${{ steps.extract_branch_pr.outputs.branch }}
        addon-id: ${{ github.event.repository.name }}
      env: # Make sure you create the below secrets (GH_TOKEN and EMAIL)
        GH_USERNAME: ${{ github.actor }}
        GH_TOKEN: ${{secrets.GH_TOKEN}}
        EMAIL: ${{secrets.EMAIL}}
